version: '2'

networks:
  default:
    external:
      name: nextgen-svcs

services:
  data:
    image: cogniteev/echo
    volumes:
    - data/:/data
    
  db:
    image: mongo:3.0
    volumes_from:
    - data
    restart: always

  matcher:
    build: ../lib/matching
    restart: always
